# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    assignees:
      - "Jamalam360"
      
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/vscode" # Location of package manifests
    schedule:
      interval: "weekly"
    assignees:
      - "Jamalam360"
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "@trivago/prettier-plugin-sort-imports"
          - "@typescript-eslint/*"
          - "esbuild"
          - "eslint-*"
          - "gts"
          - "ovsx"
          - "@vscode/vsce"
    ignore:
      # we only want to update these when they have a new feature we want
      - dependency-name: "vscode-languageclient" 
      - dependency-name: "@types/node"
      - dependency-name: "@types/vscode"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Jamalam360"
